const uprasanja = { uprasanja_slo: [
    "1. Psalm/Visoka pesem: Razložite izbrano pesem. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je pesem nastala in kaj o avtorju? Kako ste doživeli izbrano pesem? Kakšen pomen ima izbrana pesem v starojudovski (hebrejski) književnosti in kakšen v krščanstvu?",
    "2. Sofokles, Antigona: Umestite izbrani odlomek v sobesedilo in ga razložite. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem literarno delo nastalo, in o avtorju? Razložite nesoglasja med dramskimi osebami in se do njih opredelite.",
    "3. Katul, Blagoslov ljubezni/Sapfo, Svatovska pesem/Horac, Carpe diem: Razložite izbrano pesem. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je pesem nastala in kaj o avtorju? Kako ste doživeli izbrano pesem?",
    "4. Trubar: Proti zidavi cerkva: Umestite izbrani odlomek v sobesedilo in ga razložite. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem literarno delo nastalo, in o avtorju? Dokažite avtobiografske elemente.",
    "5. Boccaccio, Novela o sokolu: Umestite izbrani odlomek v sobesedilo in ga razložite. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem literarno delo nastalo, in o avtorju? Utemeljite, ali je sporočilo izbrane novele aktualno tudi za sodobnega bralca.",
    "6. Petrarka: O blažen bodi čas pomladnih dni: Razložite izbrano pesem. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je pesem nastala in kaj o avtorju? Kako ste doživeli izbrano pesem?",
    "7. Lepa Vida, Rošlin in Verjanko: Razložite izbrano pesem. Pri tem upoštevajte motivno-tematske značilnosti. Kaj veste o obdobju, v katerem je pesem nastala, in kaj o avtorju? Kako ste doživeli izbrano pesem?",
    "8. Na noviga lejta dan: Razložite izbrano pesem. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je pesem nastala, in kaj o avtorju?",
    "9. Prešeren: Povodni mož: Razložite izbrani odlomek. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je pesem nastala in kaj o avtorju? Kako ste doživeli izbrani odlomek?",
    "10. Cankar: Na klancu: Umestite izbrani odlomek v sobesedilo in ga razložite. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je literarno delo nastalo, in o avtorju?",
    "11. Shakespeare, Hamlet: Umestite izbrani odlomek v sobesedilo in ga razložite. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je dramsko delo nastalo, in o avtorju? Razložite konflikte v drami in njihov pomen za celotno besedilo.",
    "12. Kafkov Proces: Umestite izbrani odlomek v sobesedilo in ga razložite. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je literarno delo nastalo, in o avtorju? Kako ste doživeli izbrani odlomek?",
    "13. Camus: Tujec: Umestite izbrani odlomek v sobesedilo in ga razložite. Pri tem upoštevajte motivno-tematske značilnosti, slog ter zvrst in vrsto besedila. Kaj veste o obdobju, v katerem je literarno delo nastalo, in o avtorju? Kako ste doživeli izbrani odlomek?",
  ],
  uprasanja_mat: ["Kaj je izjava? (1 točka)",
    "Kaj je negacija dane izjave? Kdaj je negacija pravilna (resnična) in kdaj nepravilna (neresnična)? (1 točka)",
    "Kaj je konjunkcija izjav? Napišite pravilnostno (resničnostno) tabelo za konjunkcijo. (2 točki)",
    "Kaj je disjunkcija izjav? Napišite pravilnostno (resničnostno) tabelo za disjunkcijo. (2 točki)",
    "Kaj je tavtologija? (1 točka)",
    "Kaj je implikacija izjav? Napišite pravilnostno (resničnostno) tabelo za implikacijo. (2 točki)",
    "Kaj je ekvivalenca izjav? Napišite pravilnostno (resničnostno) tabelo za ekvivalenco. (2 točki)",
    "Povejte primer dveh izjav in ugotovite pravilnost (resničnost) njune ekvivalence. (1 točka)",
    "Kaj je prazna množica in kaj je univerzalna množica? (2 točki)",
    "Kaj je komplement množice? Kako označimo komplement in kako ga grafično predstavimo? (2 točki)",
    "Kaj je razlika dveh množic? Kako označimo razliko dveh množic in kako jo grafično predstavimo?"],
  uprasanja_ang: ["Kaj je osnovna struktura angleške povedi?",
    "Kateri so glavni časi v angleščini?",
    "Kako se oblikujejo vprašanja v pretekliku?",
    "Kaj so nepravilni glagoli in zakaj so pomembni?",
    "Kakšna je razlika med 'some' in 'any'?",
    "Kako uporabljamo člen 'the' v angleščini?",
    "Kakšna je razlika med 'who' in 'whom'?",
    "Kako tvorimo stopnjevanje pridevnikov?",
    "Kdaj uporabljamo glagole 'do', 'does' in 'did'?",
    "Kako se pravilno uporablja prihodnji čas v angleščini?"]}
  
  export default uprasanja